### PR TITLE
Bigger Workshop Doors

### PR DESCRIPTION
**Pull request by AllCorruptingWyrm**
## About The Pull Request
This PR makes the carpets look symmetrical. That's it. My OCD was bothering me.
image

## Changelog
:cl:
add: Added a double door to stronghold workshop.
/:cl:

### CODE REVIEW

**Comment by ThePainkiller** [comment]
I'm sorry, I legit didn't want to make the area carpeted because I thought the bioreactor would get scrapped, considering the Custodians don't deal with biomatter

Turns out they do, they just renamed LIQUID biomatter to "scorch" and that's how they get biosilk and carbon polymer.

**Comment by AllCorruptingWyrm** [comment]
> I'm sorry, I legit didn't want to make the area carpeted because I thought the bioreactor would get scrapped, considering the Custodians don't deal with biomatter
> 
> Turns out they do, they just renamed LIQUID biomatter to "scorch" and that's how they get biosilk and carbon polymer.

dw about it. Your good! Your contributions are valued (as always) :)

How it looks in game (I matched the tiles in the worskshop itself)
image

**Comment by Trilbyspaceclone** [comment]
can you ghost view no darkness get a screen shot on how that looks?

**Comment by AllCorruptingWyrm** [comment]
> can you ghost view no darkness get a screen shot on how that looks?
yeah sure

image
image

**Comment by ThePainkiller** [comment]
Suggestion: Add the border markings for the black carpet when ending next to a door
image

It would look like this:

image

**Comment by AllCorruptingWyrm** [comment]
I'll do that in a future PR, I kind of wanna cut down on my branches for the cargo PR.

> Suggestion: Add the border markings for the black carpet when ending next to a door image
> 
> It would look like this:
> 
> image

**Pull request merged**
