### PR TITLE
cloning + organs changes

### PR DESCRIPTION
**Pull request by Dissentbay**
## About The Pull Request
<details>
<summary>
	

- [x] cloning "works" (can't test alone in a server but codewise it's fine, and old)
- [x] you need biomatter* to clone someone (*biomatter comes in organs printed from the organ fabricator)
- [x] old organ/prosthetic printer got deleted (waiting on medical players to alert me if other printed organs will cause issues in the case of a transplant)

</summary>
<hr>

by the way, we only can't clone right now due to mapping issues, /obj/machinery/computer/cloning is required to operate it, not the hex genetics stuff AFAIK
<hr>
</details>

## Changelog
:cl:
del: surgery organ printer and prosthetics printer
tweak: old cloning pod eats organs to clone people now

/:cl:

### CODE REVIEW

**Comment by Dissentbay** [comment]
btw got approval from medical catboy

**Comment by ThePainkiller** [comment]
Approved of course, I just wish to know what's going to be the consensus on biomatter acquisition as the church branch is trying to replace it with other stuff

If we can recycle meat and shit products on a lathe it might be a welcome change, I'll have to implement IC guidelines on cloning ethics though

**Comment by Dissentbay** [comment]
you will have to talk to lamas, but I think the new medical printer, the one who prints gauze and other stuff, may be able to feed on biomatter products

**Comment by Dissentbay** [comment]
also the organ lathe printer eats organs, so a monkey cube goes a long way

**Comment by ThePainkiller** [comment]
> you will have to talk to lamas, but I think the new medical printer, the one who prints gauze and other stuff, may be able to feed on biomatter products

I'll also have to talk to Lamas about literally going over me on medical matters, unlike you who literally pinged, asked, and even waited for my go-to to do this PR.

**Comment by Dissentbay** [comment]
also all in all biomatter is in sort of a pickle right now
no one is really producing it
if it comes to a shortage I will just enable the smelter to be able to handle biomatter, no idea who will have the disposal line, but whoever it is will have a slow, but steady, source of it

**Comment by ThePainkiller** [comment]
> also all in all biomatter is in sort of a pickle right now no one is really producing it if it comes to a shortage I will just enable the smelter to be able to handle biomatter, no idea who will have the disposal line, but whoever it is will have a slow, but steady, source of it

Make it at least science, anything but giving cargo more exclusivity over shit like this, please.

**Comment by Dissentbay** [comment]
guild still has the breakers, 99% because it's a source of early plasteel, not to be used as intended

but the issue of science having biomatter production can be pointed out to xenoflora

please no more soybean spam 😔

**Pull request merged**
